apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sbudhwar-1-tenant/devfile-sample-3/devfile-sample-python-basic@sha256:7da64e4ed1f01b1974036198ff0600b908f3d19e9dc10a6dcd02ec808c313fbb
        name: my-python
        resources: {}
status: {}
